### ISSUE TITLE
Name change proposal for the Unity 8 fork: "Yutani"

### ISSUE THREAD

**Issue by volkertb** [yunit-io/yunit#11]
Should the consensus be that the Unity 8 fork were to be renamed, whether for legal reasons or just to make a fresh start, *please* consider "Yutani" as the forked project's new name! 😃

I know that the debate on whether or not to migrate the Unity 8 fork from Mir to Wayland is still ongoing as of this writing (see issue #2). However, a possible association with Wayland wouldn't be the only reason why this would be a cool and fitting name. Unity also happens to be just one letter 'a' short of being an anagram for Yutani. (Yes, I know "Wayland" is spelled differently from "Weyland", but that's still close enough for people to get [the pop culture reference](https://i.imgur.com/r5G0L.jpg).)

I'm not sure if there would be trademark or copyright issues to worry about with this proposed name change, but given that Yutani is apparently a common Japanese surname, chances are that it would be okay, right? I'm sure we could have some legal expert look into it first.

This is a serious proposal. This name change would likely be considered cool, nerdy and create a lot of much-needed positive buzz in the FOSS community, which would help kickstart this fork.

At any rate, thank you for entertaining the idea and the best of luck with the fork! Keep up the awesome work!

**Comment by m8m5** [comment]
if it is necessary to rename, I will vote for "comm**unity**"

**Comment by jsalatas** [comment]
I like "commUnity" :)

**Comment by jsalatas** [comment]
But I also like the unity8org which resembles the renaming of X11 to Xorg :)

**Comment by tengwarscribe** [comment]
If I may add my two cents, I propose calling this project Harmony. 
I have two reasons for this:
1. It's more in line with the spirit of the original name, Unity.
2. It's a reflection of the time when Canonical sought to reestablish good relations with the greater GNU/Linux community.

That being said, Yutani would be an excellent name for a Wayland compositor this DE could one day run on.

**Comment by Salmon-Bard** [comment]
Call it unityU since it is for all all of you how want convergence to be opensource and free to develop and use on any computing device.

**Comment by Flohack74** [comment]
I like Yutani - could be a name of a series: unity8org "Yutani" series :)

**Comment by bobblkabb** [comment]
**C**omm**UN**i**TY**

**Comment by auvipy** [comment]
CommUnity <3

**Comment by michaelkisiel** [comment]
+1 Yutani

**Comment by unixfox** [comment]
Umanity?

**Comment by markures** [comment]
Unityorg isn't really the best, also commUnity imho. I think that Yunit (Your Unity)  or something like that. For me, the name should be simple and should sound like the previus project so that it can be easily recognized.

**Comment by bewresu** [comment]
Mutiny?

**Comment by tomacaster** [comment]
There is no rational reason to change Unity's name. Everybody knows that name. IMHO we should talk with Canonical about rights to Unity name.

**Comment by auvipy** [comment]
agree with @tomacaster

**Comment by tomacaster** [comment]
We should stay with "old" name, migrate to Wayland and take Ubuntu as base system. Maybe this project will become official Ubuntu flavour with all canonical community and support. "Fresh start" will be the death for this project.

**Comment by bobblkabb** [comment]
Unity is a synonym for a tremendous failure. At least add a "libre" or "next"!

**Comment by markures** [comment]
You're right tomacaster. If there is no problem with the name, we should keep it. Migrate to Wayland could be hard, but it's not impossible. Unity must survive as a DE, so Mir is not necessary at all.

**Comment by tomacaster** [comment]
This is your opinion @bobblkabb. I like Unity, its simple, stable and fast. Unity is base DE in most popular linux distro not without reason. This way we can take away a large part of the community.

**Comment by bobblkabb** [comment]
@tomacaster I like it too. Wasn't talking about the software but the name.

**Comment by tomacaster** [comment]
Unity is very popular name. It guarantees great start with big community.

**Comment by mitcoes** [comment]
Being a community edition, I vote for CommUnity (CU) or CommUNnity (CUN) or CommUNity (CUNY)

I also  consider important to make a good GUI where to select the base and add the drivers for a device easily (as easy as selecting the files) and have as much device images as possible beginning with the most open and sell SoCs as the Qualcomm Snapdragon 820/1 and the Amlogics in TV boxes.

And as Sailfish has, Android apk compatibility 

And as Amazon has an APK shop in order to fund the project.

Cheap ARM TV boxes are a great market as Android apks are not usually adapted to IR or bluetooth gaming devices. 

Retroarch and  other emulators and GNU/Linux games can be a great deal selling pre installed "Community" TV boxes, dual boot with Android, or root and replace OSs for this retro gaming use.

**Comment by tim-sueberkrueb** [comment]
I vote for sticking to "Unity" (without the org) or - if necessary to rename it - "Yutani" :) commUnity sounds silly to me. But that might be only me.

**Comment by Patola** [comment]
+1 Yutani

**Comment by epictesla** [comment]
I would like the project to keep the Unity/unity8 name or go with @bobblkabb proposal of UnityNext

**Comment by CreamyCookie** [comment]
I think it's important to choose a name that is easy to search for. That isn't the case for either "unity" (game engine comes up) nor "UommUnity".

**Comment by z3ntu** [comment]
commUnity kinda sounds like communism + unity 😆

**Comment by ToxicDragon** [comment]
CommUnity +1 also offers the possibility to easily add version numbers (unity8org is limitating this convention). 

Aldingen libre to unity8org would also be quite nice! Or: Librety ;)

**Comment by man0s** [comment]
All the way to CommUnity +1:

**Comment by xadagaras** [comment]
+1 Yutani. Any name version of community is just silly. It is not very search friendly on google because the search is case insensitive. 

I have no problem with sticking with unity, if it's allowed by canonical. I don't know if there are any trademarks on this name.

**Comment by jsalatas** [comment]
Is there any way we can vote? Maybe a website that offers the ability to create polls? Can someone take care of this? :)

**Comment by linuxArtizan** [comment]
+1 UnityNext because unity8's codename was [UnityNext](https://wiki.ubuntu.com/UnityNextSpec) 

And to also keep "Unity" in the name to resemble the initial aim of the project, a converged system that adapts to all the different form factors with one codebase aka "Unity" between all systems.

And to still be easy for others to discover it now that the project has been dropped by Canonical.

**Comment by Rodney78** [comment]
http://www.strawpoll.me/12696619 A poll with the proposed names as they appeared in the conversation

**Comment by linuxArtizan** [comment]
@Rodney78 please also add UnityNext

**Comment by jsalatas** [comment]
Thanks! 
I'm not sure about "Unity" and "Unity 8". These might be registered trademarks from canonical :\

**Comment by Rodney78** [comment]
@linuxArtizan @jsalatas It seems that there is no copyright on Unity but I understand that you don't want to take any risk https://www.ubuntu.com/legal/terms-and-policies/intellectual-property-policy

I think Unity, Unity 8 and UnityNext can be considered as registered trademarks as they were used by Canonical, right?

**Comment by jsalatas** [comment]
@Rodney78 I don't speak legalese :)

Anyway, I guess we can rename the project as many times as we like in case of any legal issues

**Comment by jsalatas** [comment]
So let's say we keep the poll running for 24 hours, just to include all time zones?

**Comment by linuxArtizan** [comment]
@Rodney78 @jsalatas can you have copyright on codenames?

**Comment by jsalatas** [comment]
@linuxArtizan This was the case with X11 which was a trademark.

**Comment by nuzzar** [comment]
I think either using a made up word (gnu, linux, google) or foreign word (mir, ubuntu, ghibli) would have more impact than using an english word.

Here is some of the sugestions that I have:

Word          | Meaning             | Origin
------------- | ------------------- | -------------
Eka           | Unity               | Sanskrit
Unitas        | Unity               | Latin
Satu          | Unity/One (infix)   | Indonesian
Ubunye        | Unity               | Zulu
------------- | ------------------- | -------------
Aditi         | Freedom             | Sanskrit
Libertas      | Freedom             | Latin
Merdeka       | Freedom             | Indonesian
------------- | ------------------- | -------------
Saha          | Community (prefix)  | Sanskrit
Communitas    | Community           | Latin
Komunitas     | Community           | Indonesian
Masyarakat    | Community           | Indonesian
------------- | ------------------- | -------------
CUNT          | ^_^                 | CommUNiTy

Disclaimer: Based on online results so take it with a grain of salt.

I like 'Unitas' best.

**Comment by dtmonterrey** [comment]
Unitas sounds good to me too!

**Comment by linuxArtizan** [comment]
@jsalatas well the original version had Unity and Next as separate words, does that make a difference?

**Comment by jsalatas** [comment]
@linuxArtizan as I wrote some comments above, I don't speak legalese :)

**Comment by nuzzar** [comment]
Regarding the Unity name don't forget it's also being used by one of the big game engine. So it's less searchable without a brand name like Ubuntu.
https://unity3d.com

**Comment by Rodney78** [comment]
Can't change the poll after sharing it, it is a bit unfair for those who already vote (and I really can't BTW :) )

If some people prefer to have a latin word (or from other origin) instead of an English one, please write it here.

**Comment by jsalatas** [comment]
@nuzzar commUnity is harder that unity to search, but in any case I like it ;)

**Comment by jsalatas** [comment]
@Rodney78 we will never decide that way, if people keep posting new names :\

**Comment by Rodney78** [comment]
@jsalatas Just adding it if it make a consensus here. It is why I don't already make a new poll adding UnityNext and Unitas.

**Comment by linuxArtizan** [comment]
@jsalatas search commUnity on Google or other search engine and see what comes up, don't you think it will get lost between the other results just as @xadagaras said 

> Any name version of commUnity is just silly. It is not very search friendly on Google because the search is case insensitive.

**Comment by jsalatas** [comment]
@Rodney78 so eventually there will be a new poll, including any new proposals? :\

**Comment by jsalatas** [comment]
@linuxArtizan I like commUnity in any case. 

lol it would be really hard to get even if you try to combine with other keywords (eg "linux commUnity") :p

**Comment by Rodney78** [comment]
@jsalatas Only if a lot of people want to see a new name in the poll. At the moment I think this one is totally sufficient.

**Comment by WernerLDev** [comment]
Looks like Yunit is in the lead in the poll. I do like the name 'Yutani' as well, but wouldn't mind if the project would stick with Unity.

**Comment by dotevo** [comment]
I will add one brick more to this very long thread 
Unueco - Unity en Esperanto

**Comment by jsalatas** [comment]
@dotevo so you want a new including your propasal? :\

**Comment by Rodney78** [comment]
Yunit is in first place with 40% of the vote after one hour and a half. Second is commUnity with 13%.

**Comment by jsalatas** [comment]
@Rodney78 I guess Yunit is your choice :p

**Comment by nuzzar** [comment]
@jsalatas Wouldn't it be better to prolong the duration of the poll until next week? This way we could get a lot more voters from a regular users like myself when news site spread the poll around.

Just in case you decided to redo the poll I would like Unitas to be included.

**Comment by jsalatas** [comment]
@nuzzar yeah! no problem with the duration of the poll!

**Comment by Rodney78** [comment]
@jsalatas haha to be honest, I don't really like it ^^ Librety is now second BTW.

**Comment by dotevo** [comment]
@jsalatas Neee... But so many proposals that I wanted to add something :) Yunit is cool

**Comment by giorgosioak** [comment]
@Rodney78 Yunit is very close to Unity, Librety is a cool name but its not clear at first sight that is an Unity8 fork :)

**Comment by xadagaras** [comment]
@giorgosioak if you read Mate, you don't read out of the name that this is a Gnome 2 fork, do you?

**Comment by mrnhmath** [comment]
I like commUnity, OpenUnity or unity.org

**Comment by markures** [comment]
Wow, Yunit (Unite) is first! I knew it !

**Comment by linuxArtizan** [comment]
@mrnhmath OpenUnity sounds about right, now that it's no longer in Canonical's control. I like that

**Comment by bungcip** [comment]
just **community** is fine. not need weird spelling like **commUnity**

**Comment by markures** [comment]
I think that is strange call a project community. "Wow you know? community 2.2x has come out!"

**Comment by z3ntu** [comment]
The name `community` or `commUnity` is very bad for finding the project with search machines (eg Google).

**Comment by markures** [comment]
When will the votation end?

**Comment by markures** [comment]
When will the votation end? After 24h?

**Comment by jsalatas** [comment]
I would say 24h, but whatever. I don't care assuming that there will not be again 10 different proposal because in that case we will have to vote for the duration of the previous voting :p

**Comment by markures** [comment]
I think that someone is pushing unity8org, in 7-8 hours, it gains soo much votes

**Comment by linuxArtizan** [comment]
Don't you guys think OpenUnity would be the best choice here to represent the fact that now Unity in no longer in Canonical's maintenance? And that it also sounds good togheter with the mains os like Ubuntu OpenUnity

**Comment by cnxsoft** [comment]
Yunity. It keeps the same pronunciation, but easier to look up in search.

**Comment by markures** [comment]
LinuxArtizan but Unity has always been Open. It was only developed by programmers working for Canonical.

**Comment by linuxArtizan** [comment]
@markures I know that it has always been an open-source project, just that at this point is personal preference...

**Comment by z3ntu** [comment]
unity8org has gotten over 50 votes in the past couple of hours... I also wonder where the strawpoll link has been shared that it already has over 1400 votes (as this comment thread has "just" 74 comments from 30 people)

**Comment by Rodney78** [comment]
It has been posted here https://www.reddit.com/r/linux/comments/643cgn/unity8_fork_is_looking_for_a_name/

There is an IP duplication checking but I can't do more to avoid people from cheating. Also there is multiple option so it's not 1400 users, it's 1400 choices.

**Comment by michaelkisiel** [comment]
Unity Z ....as a reference to the dev names of our ubuntu phones :)

**Comment by fneroo** [comment]
Fork + Unity = Funity

**Comment by markures** [comment]
24 hours are passed, Yunit is first, unity8org second, Librety third.

**Comment by Rodney78** [comment]
24 hours elapsed (18.09 UTC) and the winner is: Yunit with 561 votes.

**Comment by jsalatas** [comment]
Hi Guys! 

Currently we have 
Yunit 561
unity8org 553

I'm not so eager to proceed with the rename to Yunit, given the close number of votes and the complaints above regarding cheating, but whatever. I think we are investing too much time and effort on irrelevant issues here :)

I just hope that we can keep the domain unity8.org and not setup a new one :\

**Comment by markures** [comment]
Well the aim of the votation was to change the name. A lot of people voted, even someone more times. But we must admit. Yesterday the first was Yunit. For something, unity8org gained in less hours a lot of votes. I don't want to think malicius, so the word goes to the others. For me Yunit is good because :
1) Remembers obviusly Unity
2) Doesn't cause problem of trademarks
3) People who will search for Unity, will find surely Yunit in no time.
Now is your choice =P

**Comment by Rodney78** [comment]
Totally agree with you, if we do polls, we have to respect them even if the result is not what we personally prefer. So the new name is Yunit and we will have to find a logo for this project.

**Comment by jsalatas** [comment]
Do you want to have a new domain for it? Maybe yunit.org?

**Comment by jsalatas** [comment]
Oh! forget the yunit.org domain. It's already registered.

**Comment by z3ntu** [comment]
.io? ^^

**Comment by markures** [comment]
Also yunit.com . I think that there are easy solutions

**Comment by jsalatas** [comment]
I just registered yunit.io 

It will take me some time to set it up. Will let you know when it's done.

**Comment by linuxArtizan** [comment]
@jsalatas @markures how does Yunit obviously resemble Unity and how people who will search for Unity will "surely" find Yunit? I think it's a bad name and w should follow @tomacaster's advice 

> There is no rational reason to change Unity's name. Everybody knows that name. IMHO we should talk with Canonical about rights to Unity name.

**Comment by jsalatas** [comment]
@linuxArtizan we voted for it. I'm not happy with the result either, but please let's move to the actual developing :)

**Comment by jsalatas** [comment]
I believe we are done! Website, mailing list and github organization/repo names are updated to yunit.io

Hope that makes everyone happy :)

**Comment by KylePiira** [comment]
Subreddit updated too: https://www.reddit.com/r/Yunit/

**Comment by linuxArtizan** [comment]
but why not Yuniti(with an i at the end) to actually resemble the old Unity?

**Comment by jsalatas** [comment]
@linuxArtizan I don't care. :p
I just care about moving on with the code. Hopefully at sometime soon :)

**Comment by linuxArtizan** [comment]
Well it kinda matters because just as the initial proponent(@markures) of the name said and I quote him

> the name should be simple and should sound like the previous project so that it can be easily recognized

for which this one doesn't, at least without the "i" at the end of Yunit

**Comment by jsalatas** [comment]
@linuxArtizan ok. So what do you propose about this?

**Comment by jsalatas** [comment]
@markures we need your feedback 

https://www.reddit.com/r/Yunit/comments/649qj8/yunit_pronunciation/
