### ISSUE TITLE
Step Zero

### ISSUE THREAD

**Issue by ShFil119** [yunit-io/yunit#18]
I've been thinking and I found a problem. There are a lot of features we want to implement. But no one knows how long it takes. Half a year? Year? 

Being in stage of evolution, means there's no enough mature functionality to use. 

For mobile users(like UBports) it means the project is useless.
So I think we should focus on leading to a usable state and removing trade marks. After that create branch Old to maintain simultaneously(bugs), after that think about features.

**Comment by aissat** [comment]
@ShFil119  I agree with you

**Comment by Flukas88** [comment]
Hi there.

I'd say 

**master** (the codebase)
**devel** (where both projects will commit)
**desktop-devel** for us
**mobile-devel** for UBports

**Comment by jsalatas** [comment]
Please use our mailing list for discussion regarding development

https://yunit.io/cgi-bin/mailman/listinfo/dev
