### ISSUE TITLE
Issues to discuss

### ISSUE THREAD

**Issue by jsalatas** [yunit-io/yunit#19]
Hey guys! 

First of all thanks for your interest in continuing working with unity 8. 

There are some thinhs I would like to discuss: it seems that we are currently using github's issues as a general discussion list. It's ok with me if you want to do so, but I'm afraid that this will create a mess in the long rub. Think when we start development and we have real issues with the code along with all the other general discussions. Issues with the code will eventually be fixed and closed, but does a discussion ever close? For now I leave all discussions open but this will eventually lead us to a situation having hundreds of open discussions and struggling with these along with the real code issues. I would love to hear your thought on this.

Also, as unity8org is an organization now (as per your suggestions), we can add more people who can maintain stuff here (currently I'm the only member). Is someone interesting to be added?

**Comment by ShFil119** [comment]
Forum?

**Comment by jsalatas** [comment]
@ShFil119 do you want to handle it? :)

I can setup one for you at some subdomain/directory at http://unity8.org or you can create it where ever you like. 

I guess we will need more moderators, unless you can take care of it by yourself :)

**Comment by jsalatas** [comment]
In general we need more people to manage the various aspects of the project.

**Comment by ShFil119** [comment]
I think something like fluxbb will be more than enough. I can try to set up tomorrow.

**Comment by jsalatas** [comment]
Great! Do you want me to set it up at lets say http://forum.unity8.org and grant you admin rights?  
Unfortunately I cannot give you shell access to the server :)

**Comment by ShFil119** [comment]
And some db like MySQL/PostgreSQL/SQLite. ;)

**Comment by jsalatas** [comment]
Of course! MySQL and phpMyAdmin. Are you OK with this? If so I need your email to email you your credentials. 

Also there seem to be a github external authentication module for fluxbb, I guess we should install this too :)

**Comment by jsalatas** [comment]
Please confirm you are ok with the above

**Comment by ShFil119** [comment]
Ok. I will try. ;)

**Comment by jsalatas** [comment]
OK! Please send me an email to info@unity8.org, so that I can have your email address, and also include your name if you like :)

**Comment by mixedCase** [comment]
Can we consider Discourse? It should be simple to install and maintain; plus it looks more modern.

**Comment by jsalatas** [comment]
@mixedCase set it up, and the people will decide which one to use. :)

**Comment by RUSshy** [comment]
For forum please consider [Discourse ](https://try.discourse.org/) or [Flarum ](https://discuss.flarum.org/) they are modern

**Comment by jsalatas** [comment]
Again, set it up, let us know about it, and let the people decide :)

**Comment by mixedCase** [comment]
I don't have a server for it. But I don't have an issue doing the set-up on one available for the project.

**Comment by jsalatas** [comment]
Oh! my bad! I thought that it was offered as a service. 

I could install these in my server. 

@ShFil119 already offered to help with fluxbb and now we have two other options: Discourse and Flarum. 

Do you want to vote for it? Of course if we choose one, the person who proposed that, should manage it after I set it up? :)

**Comment by sh4nks** [comment]
I'd say go with FluxBB (or with FlaskBB.. shameless self advertising :)) - Maybe I am getting old but I think its quite difficult to have an overview of the stuff with the layout all those new discussion boards are having.

**Comment by jsalatas** [comment]
In any case we need to agree on something :)

**Comment by WernerLDev** [comment]
Discourse and flarum both look quite nice. Another suggestion I would like to add is MyBB. https://mybb.com/ 

Maybe we should start another poll? :P

**Comment by labsin** [comment]
I also like discourse.
That or mailing list (everyone has an email and you can use your own preferred way of managing it)
The big downside of mailing list is it's not a good platform looking for answers for questions already answered.
But I hate it when there are multiple platforms. As long as there is a way to follow through email a specific topic and subforum and possibly react to it trough email I'm happy.
I also think a clear separation between core development/building questions and end user questions needs to exist.

**Comment by jsalatas** [comment]
@WernerLDev if we cannot decide the poll is the only way. I suggest you get used to polls because it seems we will have many of them :)

If someone wants to start a poll, please do so and let us know :)

**Comment by WernerLDev** [comment]
Created a poll with the suggestions from this thread: http://www.strawpoll.me/12700978 :)

**Comment by jsalatas** [comment]
BTW: I assume that people who are proposing a particular software have already worked with it and they are willing to manage it. So if someone creates a poll, please add the names of the people who proposed that. :)

**Comment by jsalatas** [comment]
@WernerLDev can you please edit it and add the names of the people who proposed each one and will manage it?

**Comment by giorgosioak** [comment]
@jsalatas I would like to help

**Comment by WernerLDev** [comment]
@jsalatas I wasn't able to edit the poll so I had to create a new one.
I have also added links to the forum websites so people unfamiliar with it can check them out before voting.

http://www.strawpoll.me/12701077

**Comment by jsalatas** [comment]
nice! Thanks!

**Comment by linuxArtizan** [comment]
[What are the advantages of Flarum over Discourse?](https://discuss.flarum.org/d/676-what-are-the-advantages-of-flarum-over-discourse/4)

**Comment by KylePiira** [comment]
Why not just use a subreddit?

**Comment by giorgosioak** [comment]
@KylePiira  there is already a subreddit: https://www.reddit.com/r/unity8dev/

**Comment by KoczurekK** [comment]
@KylePiira We already have subreddit, `/r/unity8dev/`.

**Comment by KylePiira** [comment]
@KoczurekK Yes I'm aware that's why I mentioned [/r/Unity8dev](https://www.reddit.com/r/unity8dev/) in my comment.

**Comment by jsalatas** [comment]
Hey guys!

sorry, my bad: I'm afraid I need to exercise my "veto powers" regarding Discourse:  just noticed that this is a ruby based software and the current server that is hosting unity8.org doesn't have support for ruby (php only). I could have ruby support but this is not a road I want to take : \

Is it really so important to have Discourse? :\

**Comment by jsalatas** [comment]
Same for flaskbb which is python :\

Also flarum seems to be in a prerelease version (v0.1.0-beta). Do you think it is good idea to use it? :\

Again, sorry I didn't check these issues earlier :(

**Comment by linuxArtizan** [comment]
@jsalatas Flarum seems the way to go as it is php based and even tough it is in beta it's actively developed, just yesterday version 0.1.0-beta.6 was released and besides that it has extensibility with extensions, the UI is just as modern and much faster than Discourse. Check the link below to see the advantages over Discourse

> [What are the advantages of Flarum over Discourse](https://discuss.flarum.org/d/676-what-are-the-advantages-of-flarum-over-discourse/)

Either that or to use the subreddit with a more modern theme.

**Comment by sh4nks** [comment]
I'd also vote for reddit. But if something selfhosted is prefered, I'd say go with FluxBB or MyBB because they seem to be quite stable (and you can run both of them on your machine bc they are written in PHP).

**Comment by jsalatas** [comment]
@linuxArtizan 

1) I'm afraid I need to constantly keep an eye on it for updates (I guess there will be security issues).
2) As per my understanding this is a new software, and we don't know if it will succeed ans still be actively developed after (let's say a year). 
3) In general I don't find good the idea to base our communications on software in it's early stages.

Finally, I don't want to spend any more time on this really irrelevant issue, I just don't want to have general discussions here in github. So those who think that the communication platform we use is really so important issue, please decide yourselves and let the rest of us know  :)

**Comment by linuxArtizan** [comment]
@jsalatas then reddit should be,  /r/Unity8 for general discussions and /r/Unity8dev for development, but please use the same theme for /r/Unity8dev

**Comment by KylePiira** [comment]
@linuxArtizan Alright I've updated the theme on [/r/Unity8dev](https://www.reddit.com/r/unity8dev/)

**Comment by jsalatas** [comment]
Ubuntu's Theme might be copyrighted. Please make sure we are not violating this 

"Canonical owns intellectual property rights in the trade dress and look and feel of Ubuntu (including the Unity interface), along with various themes and components that may include unregistered design rights, registered design rights and design patents, your use of Ubuntu is subject to these rights."

https://www.ubuntu.com/legal/terms-and-policies/intellectual-property-policy

**Comment by KylePiira** [comment]
@jsalatas I'll look into this.

**Comment by jsalatas** [comment]
Obviously you need to modify their names according to name change of the project :)

https://github.com/unity8org/unity8org/issues/11

**Comment by jsalatas** [comment]
Can someone inform me about the correct subreddit url so that I can update our website? I'm a little bit lost here :\

Thanks!

**Comment by KylePiira** [comment]
@jsalatas Assuming we are sticking with the name Yunit (hopefully) then its /[r/Yunit](https://www.reddit.com/r/Yunit/)

**Comment by jsalatas** [comment]
@KylePiira thanks! 

I guess I'll stick with the name. Anyone interesting in changing it, need to create a new fork :p

**Comment by jsalatas** [comment]
OK. Home page updated. Please read the various contact method and be sure you post in the right place. Any irrelevant messages could be removed at our discretion :p

https://yunit.io/

**Comment by KylePiira** [comment]
@jsalatas seems to still be using the old subreddit.

**Comment by jsalatas** [comment]
@KylePiira my bad! sorry :(

Fixed

**Comment by jsalatas** [comment]
I'm closing it. Please use the correct communication channels as described at https://yunit.io
