### ISSUE TITLE
Migrate to Wayland

### ISSUE THREAD

**Issue by dgmvecuador** [yunit-io/yunit#2]
I dont know if its a good idea to use **MIR** now, **Wayland** its the future now.

I know that **MIR** is an API and **Wayland** a protocol, but **Wayland** has a big community, and to have less component to mantain its always welcome for a project.

**Comment by Rodney78** [comment]
Agree on that. Maintaining two projects at the same time seems to be too much work and may be a failure.

**Comment by jsalatas** [comment]
Yeah. This is also my idea. To completely ditch Mir and use wayland. Also I believe at least at first place, we should focus more on the desktop part and not in mobile.

**Comment by Goddard** [comment]
This makes the most sense and reduces required resources.  UBPorts has already said they want to keep it alive along with Ubuntu phone.

**Comment by m8m5** [comment]
an idea from reddit user [blackout24](https://www.reddit.com/r/linux/comments/63rwkm/unity8org_a_fork_of_ubuntu_unity8/dfx1628)

> You could probably use the QtCompositor API and migrate the Unity 8 Shell, which is QML to run on it. You can write a barebones Wayland Compositor in pure QML using QtCompositor with only a handful lines of code.
https://doc.qt.io/qt-5/qtwaylandcompositor-index.html
https://doc.qt.io/qt-5/qtwaylandcompositor-pure-qml-example.html

**Comment by KoczurekK** [comment]
Seems like a standard and logical approach, +1. Btw IMHO this issue should be fixed as fast as possibly, there's no way we can manage maintain 2 so big projects.

**Comment by xadagaras** [comment]
+1 from me. I don't know if there is already support for **Wayland**, but keeping **Mir** and **Wayland** support at the same time might be to much overhead for such a small team.

**Comment by rolandixor** [comment]
There really is no point to maintaining support for Mir anywhere. Let it die.

**Comment by jsalatas** [comment]
Can we please continue the discussion at the mailing list? :)

https://unity8.org/cgi-bin/mailman/listinfo/dev

**Comment by adlocode** [comment]
I agree. Wayland is the standard protocol. It's the only way forward.

**Comment by Sunderland93** [comment]
Mir does not make any sense. It hard for development, because all of he's components are not in upstream (QtMir, XMir, MirGTK, MirSDL)

**Comment by m8m5** [comment]
>So, don’t simply fork Unity8 and plan to get it working on Wayland. You’ll end up with a single wall that falls over before you’ve replaced the rest of the building. (Sorry, I went back to “metaphor”.)

http://voices.canonical.com/alan.griffiths/2017/04/07/the-end-of-a-dream/

**Comment by bregma** [comment]
> Mir does not make any sense. It hard for development, because all of he's components are not in upstream (QtMir, XMir, MirGTK, MirSDL)

Well, for the record, the the Qt Mir QPA is upstream, GTK+ support is upstream, libSDL2 support is upstream, and Xmir is a leaf-node application not a toolkit so it is its own upstream.  None of what you said is correct.

**Comment by kirylpl** [comment]
Support this. It seems the only way to continue development of Unity desktop environment and save developers from tons of work with own graphical stack.

**Comment by stavpup** [comment]
m8m5 I wonder if it is easier to use Gnome Shell with extensions to build the same UI experience

**Comment by Xarcell** [comment]
I also think we should adopt Wayland and abandon Mir.

**Comment by jsalatas** [comment]
Please use our mailing list for discussion regarding development

https://yunit.io/cgi-bin/mailman/listinfo/dev
