### ISSUE TITLE
Will This Fork Allow For Convergence?

### ISSUE THREAD

**Issue by Xarcell** [yunit-io/yunit#21]
I was wondering by forking Unity8, will this work for convergence? Or would that require a fork of the OS as well? Sorry, not a programmer and new to Ubuntu.

**Comment by KoczurekK** [comment]
This in just a shell, not whole OS. But yes, we will keep developing mobile mode and convergence.

**Comment by KAMiKAZOW** [comment]
Well, Canonical also developed some applications using a custom toolkit for Qt. You should ask yourself if you want to maintain those, too.

An alternative would be to pick up Kirigami which encourages a somewhat different design of apps but at least is in active development.

**Comment by jsalatas** [comment]
Please use our mailing list for discussion regarding development

https://yunit.io/cgi-bin/mailman/listinfo/dev
