### ISSUE TITLE
Build.sh Feedback

### ISSUE THREAD

**Issue by giorgosioak** [yunit-io/yunit#22]
In case you try to build and you have feedback please add a comment here 😃

**Comment by giorgosioak** [comment]
I run ./build.sh in a virtual machine with ubuntu 17.04 zesty zapus beta 2 and I've got an error:

CMake Error at CMakeLists.txt:65 (find_package):
  By not providing "FindQt5Core.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5Core", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5Core"
  (requested version 5.6) with any of the following names:

    Qt5CoreConfig.cmake
    qt5core-config.cmake

  Add the installation prefix of "Qt5Core" to CMAKE_PREFIX_PATH or set
  "Qt5Core_DIR" to a directory containing one of the above files.  If
  "Qt5Core" provides a separate development package or SDK, be sure it has
  been installed.


$./build.sh output: https://paste.ubuntu.com/24341309/
~/unity8org/builddir/CMakeFiles/CMakeOutput.log: https://paste.ubuntu.com/24341318/

**Comment by KoczurekK** [comment]
I had to set `CMAKE_PREFIX_PATH` to `/opt/Qt/5.8/gcc_64/lib/cmake`, then it worked. Yet I have another problem:

**Comment by alekseyt** [comment]
@giorgosioak try to rm -fr builddir, then ./build.sh again. Make sure that you have equivs installed. The underlying problem might be that it was already configured w/o equivs once, so it doesn't show you a warning and don't install dependencies.

**Comment by KoczurekK** [comment]
I resolved this problem by setting `CMAKE_PREFIX_PATH` to `/opt/Qt/5.8/gcc_64/lib/cmake`.

I have another problem, which also wasn't solved by @up suggestions.
```
-- Checking for module 'unity-shell-application=27'
--   
CMake Error at /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:367 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:532 (_pkg_check_modules_internal)
  CMakeLists.txt:74 (pkg_check_modules)


-- Configuring incomplete, errors occurred!
See also "/home/kamil/Desktop/unity8org/builddir/CMakeFiles/CMakeOutput.log".
```
[CMakeOutput.txt](https://github.com/unity8org/unity8org/files/907630/CMakeOutput.txt)

**Comment by bregma** [comment]
For a list of all the build-time dependencies actually used to build Unity 8 in CI, look at the file debian/control, and for the actual commands run look at debian/rules.  Those files are guaranteed up-to-date because they're used by the CI train and anything else might be out of date.

**Comment by alekseyt** [comment]
@KoczurekK are you on 17.04 (beta). Apparently unity-shell-application is provided by libunity-api-dev, but i don't know what minimal version required, but unity-shell-application (17.04) has unity-shell-application=27.

**Comment by bregma** [comment]
Yes, the upstream CI is always build against the Ubuntu archives, which would be Xenial+Overlay and Zesty+Overlay, and I'm not sure if that includes the -proposed pocket or not (Unity 8 is not my project, I'm not an expert).

The "Overlay" is a [PPA](https://launchpad.net/~ci-train-ppa-service/+archive/ubuntu/stable-phone-overlay) with newer version of the software.  This is used because for Xenial (Ubuntu 16.04) the target is a Unity 8 snap, and for Zesty the release is already frozen but the Z+1 archives are not yet open.

**Comment by giorgosioak** [comment]
So i updated my system build is working right.

**Comment by jsalatas** [comment]
so this was just an issue of updating your system and not a bug.
