### ISSUE TITLE
KDE Plasma re-implement

### ISSUE THREAD

**Issue by Mikacpikac** [yunit-io/yunit#23]
Make Unity 8 a shell that runs on top of KDE Plasma stack (Like Budgie 10 on GNOME stack). It is possible and best for developing because it uses same technologies. Sorry for very bad English.

**Comment by Mikacpikac** [comment]
I think best way to go is simillar to what LXQT does. Made shell for Plasma. Then just fork other components and rename them or stay dependent on Plasma.

**Comment by linuxArtizan** [comment]
As far as I know Unity8 is based on Gnome 3's core, if it's worth it or not it's subjective, but porting it would be a waste of time for such a small team right now

**Comment by Mikacpikac** [comment]
No. Unity 8 is written from scratch with QT and QML. That's why I said to make shell to Plasma.

**Comment by cibersheep** [comment]
Would that also help to making yunit compatible with Plasma Mobile?

**Comment by jsalatas** [comment]
We are actually considering using kwin which already supports wayland and can run on mobile phones.

**Comment by Mikacpikac** [comment]
+1 for that decision. But what with display manager/protocol is it enough
to port?

08.04.2017. 22.44, "John Salatas" <notifications@github.com> је написао/ла:

**Comment by jsalatas** [comment]
Please use our mailing list for discussion regarding development

https://yunit.io/cgi-bin/mailman/listinfo/dev
