### ISSUE TITLE
Contacting the project

### ISSUE THREAD

**Issue by jsalatas** [yunit-io/yunit#24]
I guess it is time for a clean up :)

Please make sure to read the ways of contacting our project.

https://yunit.io/

Any irrelevant message to either 3 places (mailing list, github, subreddit) may be removed at our discretion :)

**Comment by KylePiira** [comment]
Should probably close out any issues unrelated to the code from Github.

**Comment by KoczurekK** [comment]
@KylePiira Yep, it's a bit messy here. So… @jsalatas, can I?

**Comment by jsalatas** [comment]
Will do it at some time soon :)

**Comment by rolandixor** [comment]
Probably not the best place to say this, but most modern users/developers/etc are not going to be fond of a mailing list. Just a hint.

**Comment by jsalatas** [comment]
@rolandixor if they want their message to be heard, they will use it. as
"Any irrelevant message to either 3 places (mailing list, github, subreddit) may be removed at our discretion"
:)

**Comment by jsalatas** [comment]
Closing this too
