### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Mikacpikac** [yunit-io/yunit#27]
Hi everyone, I would like to help with translations. I can fully translate it to Serbian, Croatian and Bosnian. Best regards.

**Comment by giorgosioak** [comment]
Hello :) The translation files are here: https://github.com/yunit-io/yunit/tree/master/po

You can find a sr.po and use Gtranslator app to work with it. Then you can make a pull request.

**Comment by Mikacpikac** [comment]
Done!

**Comment by giorgosioak** [comment]
Merged :)

**Comment by Mikacpikac** [comment]
Thanks!

**Comment by Rodney78** [comment]
Is it normal that cro.po is not in the po folder?

**Comment by Mikacpikac** [comment]
No! It must be in.

**Comment by Mikacpikac** [comment]
@giorgosioak Ok, mistake. Move cro.po to po folder.

**Comment by giorgosioak** [comment]
ok

**Comment by Pharaone** [comment]
Moved

**Comment by KoczurekK** [comment]
I guess there's nothing more to discuss, right?
