### ISSUE TITLE
Continuous integration

### ISSUE THREAD

**Issue by jcelerier** [yunit-io/yunit#3]
The builds should be tested with Travis CI or something like this

**Comment by jsalatas** [comment]
Give me some time! I'm just trying to set things up at least in an initial level. :)

**Comment by jsalatas** [comment]
Can we please continue the discussion at the mailing list? :)

https://unity8.org/cgi-bin/mailman/listinfo/dev

**Comment by jsalatas** [comment]
Please use our mailing list for discussion regarding development

https://yunit.io/cgi-bin/mailman/listinfo/dev
