### ISSUE TITLE
First release

### ISSUE THREAD

**Issue by yenel** [yunit-io/yunit#41]
When the planned release of the first version **Yunit** ?

**Comment by Pharaone** [comment]
When yunit will be usable, and when bug #34 will be fixed, at least.

**Comment by jsalatas** [comment]
No plans yet :)

**Comment by KoczurekK** [comment]
Actually, if we count first test build as a release, we already have it.
- No idea if it works at all.
- If so, I recommend using 17.04 beta 2.
- Don't do it on normal PC, VM is highly recommended.
- To get it build I had to skip 3 tests, it's some kind of message itself.
- Not tested. And by that I mean, didn't work during any actual test, but not all cases were tried.

Unpack attachment and execute those commands in unpacked directory:
```
dpkg -i *.deb
sudo apt install -f
```
[debs.tar.gz](https://github.com/yunit-io/yunit/files/908445/debs.tar.gz)

However, it's remarkable that we actually managed to compile it and build debs, it's huge step forward.

**Comment by jsalatas** [comment]
Oh! You build deps already? Nice! I guess the names should change from unity8..... to yunit. Also version number should changee. Should we say that we are now at version 0.0.1 of yunit? :\
Finally if we change the deb packages names we should that they conflict to the canonicals unity8 deb packages.

**Comment by KoczurekK** [comment]
Right, it's absolutely on some TODO list, but I haven't thought about it yet, TBH I'd be happy to see it actually work, then I can worry 'bout packages' names. :grin:

**Comment by Pharaone** [comment]
@jsalatas yup, we are at version 0.0.1 thanks to @KoczurekK

**Comment by jsalatas** [comment]
Yeay! So @KoczurekK is now our official package maintainer? :p

**Comment by KoczurekK** [comment]
Admit it, you just wanted a person to do all packaging–related stuff, cuz no one really likes it? :package: 
Actually… no problem, I can take that role if you're all ok with that. Luckily I already looked into snaps, so I'm not gonna have *that* bad time. :grin:

**Comment by nuzzar** [comment]
For the sake of unity8 legacy why not start the version number from 8.0.1? Just for fun. Goods luck all.

**Comment by Leppan** [comment]
I'd imagine us at 0.0.0, in terms of stable releases.

**Comment by KoczurekK** [comment]
@Leppan I'd go for -0.0.1, 0.0.0 seems to be a bit optimistic. :grinning:
