### ISSUE TITLE
name mismatch

### ISSUE THREAD

**Issue by maddin200** [yunit-io/yunit#50]
minor
\plugins\Cursor\MousePointer.h line 35
declaration:
 void setCursorName(const QString &qtCursorName) override;

definition:
void MousePointer::setCursorName(const QString &cursorName)
{
    if (cursorName != m_cursorName) {
        m_cursorName = cursorName;
        Q_EMIT cursorNameChanged(m_cursorName);
    }
}

**Comment by jsalatas** [comment]
Can you fix, commit and close the issue?

Thanks!

**Comment by maddin200** [comment]
if possible it might be better someone else change the code for double checking and also correcting other issues.

**Comment by jsalatas** [comment]
OK. I'll do it tomorrow if it isn't fixed by someone else until then...

**Comment by KoczurekK** [comment]
Done.
