### ISSUE TITLE
A couple of hints about yunit.io

### ISSUE THREAD

**Issue by plastikat** [yunit-io/yunit#52]
Maybe not the best place to post this, but I've noticed the following problems with the [front page](https://yunit.io):
- On the third bullet point in "Contact us" section by "[...] please **us** the project’s issues page in github." you likely mean "please **use** the project’s issues page in github".
- The "Source Code" link in the upper right corner points to the previous repo, not this one.

**Comment by KoczurekK** [comment]
Fixed.
