### ISSUE TITLE
Can't build on Ubuntu 17.04 beta2

### ISSUE THREAD

**Issue by NicholasShatokhin** [yunit-io/yunit#61]
When I run build.sh I get an error:

-- Checking for module 'unity-shell-application=27'
--   
CMake Error at /usr/share/cmake-3.7/Modules/FindPkgConfig.cmake:415 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.7/Modules/FindPkgConfig.cmake:588 (_pkg_check_modules_internal)
  CMakeLists.txt:74 (pkg_check_modules)

But I installed libunity-api-dev

**Comment by NicholasShatokhin** [comment]
Ok, I configured it. There was unsatisfied depencies for unity8-build-deps

**Comment by NicholasShatokhin** [comment]
I see warnings when build debs:

dpkg-source: warning: Version number suggests Ubuntu changes, but there is no XSBC-Original-Maintainer field
dpkg-source: warning: source directory 'yunit' is not <sourcepackage>-<upstreamversion> 'unity8-8.15+17.04.20170328.3'

Looks like there is old values from unity8 somewhere.

**Comment by NicholasShatokhin** [comment]
One test has failed:

24/27 Test #25: Whitespace .......................***Failed    4.73 sec
/home/robotex/sources/yunit/builddir/tests/plugins/AccountsService/PropertiesAdaptor.h: bad whitespace in line 3
/home/robotex/sources/yunit/builddir/tests/plugins/AccountsService/AccountsPrivateAdaptor.h: bad whitespace in line 3
/home/robotex/sources/yunit/builddir/tests/plugins/AccountsService/PropertiesAdaptor.cpp: bad whitespace in line 3
/home/robotex/sources/yunit/builddir/tests/plugins/AccountsService/PropertiesAdaptor.cpp: multiple new lines at end of file
/home/robotex/sources/yunit/builddir/tests/plugins/AccountsService/LocationAdaptor.cpp: bad whitespace in line 3
/home/robotex/sources/yunit/builddir/tests/plugins/AccountsService/LocationAdaptor.cpp: multiple new lines at end of file
/home/robotex/sources/yunit/builddir/tests/plugins/AccountsService/SecurityPrivacyAdaptor.cpp: bad whitespace in line 3
/home/robotex/sources/yunit/builddir/tests/plugins/AccountsService/SecurityPrivacyAdaptor.cpp: multiple new lines at end of file
/home/robotex/sources/yunit/builddir/tests/plugins/AccountsService/InputAdaptor.h: bad whitespace in line 3
/home/robotex/sources/yunit/builddir/tests/plugins/AccountsService/AccountsUserAdaptor.h: bad whitespace in line 3
/home/robotex/sources/yunit/builddir/tests/plugins/AccountsService/AccountsPrivateAdaptor.cpp: bad whitespace in line 3
/home/robotex/sources/yunit/builddir/tests/plugins/AccountsService/AccountsPrivateAdaptor.cpp: multiple new lines at end of file
/home/robotex/sources/yunit/builddir/tests/plugins/AccountsService/UscInputAdaptor.h: bad whitespace in line 3
/home/robotex/sources/yunit/builddir/tests/plugins/AccountsService/AccountsUserAdaptor.cpp: bad whitespace in line 3
/home/robotex/sources/yunit/builddir/tests/plugins/AccountsService/AccountsUserAdaptor.cpp: multiple new lines at end of file
/home/robotex/sources/yunit/builddir/tests/plugins/AccountsService/AccountsAdaptor.h: bad whitespace in line 3
/home/robotex/sources/yunit/builddir/tests/plugins/AccountsService/SecurityPrivacyAdaptor.h: bad whitespace in line 3
/home/robotex/sources/yunit/builddir/tests/plugins/AccountsService/InputAdaptor.cpp: bad whitespace in line 3
/home/robotex/sources/yunit/builddir/tests/plugins/AccountsService/InputAdaptor.cpp: multiple new lines at end of file
/home/robotex/sources/yunit/builddir/tests/plugins/AccountsService/UscInputAdaptor.cpp: bad whitespace in line 3
/home/robotex/sources/yunit/builddir/tests/plugins/AccountsService/UscInputAdaptor.cpp: multiple new lines at end of file
/home/robotex/sources/yunit/builddir/tests/plugins/AccountsService/LocationAdaptor.h: bad whitespace in line 3
/home/robotex/sources/yunit/builddir/tests/plugins/AccountsService/AccountsAdaptor.cpp: bad whitespace in line 3
/home/robotex/sources/yunit/builddir/tests/plugins/AccountsService/AccountsAdaptor.cpp: multiple new lines at end of file
/home/robotex/sources/yunit/builddir/tests/plugins/SessionBroadcast/BroadcastAdaptor.h: bad whitespace in line 3
/home/robotex/sources/yunit/builddir/tests/plugins/SessionBroadcast/BroadcastAdaptor.cpp: bad whitespace in line 3
/home/robotex/sources/yunit/builddir/tests/plugins/SessionBroadcast/BroadcastAdaptor.cpp: multiple new lines at end of file
/home/robotex/sources/yunit/builddir/tests/plugins/Unity/Session/LogindManagerAdaptor.cpp: bad whitespace in line 3
/home/robotex/sources/yunit/builddir/tests/plugins/Unity/Session/LogindManagerAdaptor.cpp: multiple new lines at end of file
/home/robotex/sources/yunit/builddir/tests/plugins/Unity/Session/LogindManagerAdaptor.h: bad whitespace in line 3
/home/robotex/sources/yunit/builddir/tests/plugins/Unity/Session/LogindSessionAdaptor.h: bad whitespace in line 3
/home/robotex/sources/yunit/builddir/tests/plugins/Unity/Session/LogindSessionAdaptor.cpp: bad whitespace in line 3
/home/robotex/sources/yunit/builddir/tests/plugins/Unity/Session/LogindSessionAdaptor.cpp: multiple new lines at end of file
/home/robotex/sources/yunit/builddir/tests/plugins/Unity/Session/LightDMSessionAdaptor.h: bad whitespace in line 3
/home/robotex/sources/yunit/builddir/tests/plugins/Unity/Session/LightDMSessionAdaptor.cpp: bad whitespace in line 3
/home/robotex/sources/yunit/builddir/tests/plugins/Unity/Session/LightDMSessionAdaptor.cpp: multiple new lines at end of file
/home/robotex/sources/yunit/builddir/tests/utils/modules/Unity/Test/UnityTestQml_automoc.dir/moc_plugin_ADXQMHAXOOHDUW.cpp: bad whitespace in multiple lines
/home/robotex/sources/yunit/builddir/tests/mocks/Utils/FakeUtils-qml_automoc.dir/moc_constants_DNUAWUW6YZXSSJ.cpp: bad whitespace in line 109
/home/robotex/sources/yunit/builddir/tests/mocks/Utils/FakeUtils-qml_automoc.dir/moc_plugin_ADXQMHAXOOHDUW.cpp: bad whitespace in multiple lines
/home/robotex/sources/yunit/builddir/tests/mocks/Powerd/MockPowerd-qml_automoc.dir/moc_plugin_ADXQMHAXOOHDUW.cpp: bad whitespace in multiple lines
/home/robotex/sources/yunit/builddir/tests/mocks/LightDMController/LightDMController_automoc.dir/moc_plugin_ADXQMHAXOOHDUW.cpp: bad whitespace in multiple lines
/home/robotex/sources/yunit/builddir/tests/mocks/QMenuModel/QMenuModelQml_automoc.dir/moc_plugin_ADXQMHAXOOHDUW.cpp: bad whitespace in multiple lines
/home/robotex/sources/yunit/builddir/tests/mocks/QtMultimedia/QtMultimedia-qml_automoc.dir/moc_plugin_ADXQMHAXOOHDUW.cpp: bad whitespace in multiple lines
/home/robotex/sources/yunit/builddir/tests/mocks/UInput/FakeUInput-qml_automoc.dir/moc_plugin_ADXQMHAXOOHDUW.cpp: bad whitespace in multiple lines
/home/robotex/sources/yunit/builddir/tests/mocks/Ubuntu/Telephony/FakeUbuntuTelephonyQml_automoc.dir/moc_plugin_ADXQMHAXOOHDUW.cpp: bad whitespace in multiple lines
/home/robotex/sources/yunit/builddir/tests/mocks/Ubuntu/SystemSettings/SecurityPrivacy/MockSecurityPrivacy_automoc.dir/moc_plugin_ADXQMHAXOOHDUW.cpp: bad whitespace in multiple lines
/home/robotex/sources/yunit/builddir/tests/mocks/Ubuntu/Connectivity/connectivity-qml_automoc.dir/moc_plugin_ADXQMHAXOOHDUW.cpp: bad whitespace in multiple lines
/home/robotex/sources/yunit/builddir/tests/mocks/Ubuntu/DownloadDaemonListener/FakeUbuntuDownloadDaemonListenerQml_automoc.dir/moc_plugin_ADXQMHAXOOHDUW.cpp: bad whitespace in multiple lines
/home/robotex/sources/yunit/builddir/tests/mocks/MeeGo/QOfono/MockQOfono_automoc.dir/moc_plugin_ADXQMHAXOOHDUW.cpp: bad whitespace in multiple lines
/home/robotex/sources/yunit/builddir/tests/mocks/Wizard/MockWizard-qml_automoc.dir/moc_mockplugin_BCDU4ARKZ7IXSH.cpp: bad whitespace in multiple lines
/home/robotex/sources/yunit/builddir/tests/mocks/AccountsService/MockAccountsService-qml_automoc.dir/moc_plugin_ADXQMHAXOOHDUW.cpp: bad whitespace in multiple lines
/home/robotex/sources/yunit/builddir/tests/mocks/GSettings.1.0/FakeGSettingsQml_automoc.dir/moc_plugin_ADXQMHAXOOHDUW.cpp: bad whitespace in multiple lines
/home/robotex/sources/yunit/builddir/tests/mocks/GSettings.1.0/FakeGSettingsQml_automoc.dir/moc_fake_gsettings_PQTTEAZQYNFNWV.cpp: bad whitespace in line 112
/home/robotex/sources/yunit/builddir/tests/mocks/SessionBroadcast/MockSessionBroadcast-qml_automoc.dir/moc_plugin_ADXQMHAXOOHDUW.cpp: bad whitespace in multiple lines
/home/robotex/sources/yunit/builddir/tests/mocks/Lights/MockLights-qml_automoc.dir/moc_plugin_ADXQMHAXOOHDUW.cpp: bad whitespace in multiple lines
/home/robotex/sources/yunit/builddir/tests/mocks/Biometryd/MockBiometryd_automoc.dir/moc_MockDevice_6AFQYTELAQ4DII.cpp: bad whitespace in line 110
/home/robotex/sources/yunit/builddir/tests/mocks/Biometryd/MockBiometryd_automoc.dir/moc_plugin_ADXQMHAXOOHDUW.cpp: bad whitespace in multiple lines
/home/robotex/sources/yunit/builddir/tests/mocks/Unity/Screens/MockScreensPlugin_automoc.dir/moc_plugin_ADXQMHAXOOHDUW.cpp: bad whitespace in multiple lines
/home/robotex/sources/yunit/builddir/tests/mocks/Unity/FakeUnityQml_automoc.dir/moc_fake_unity_plu_L35HB3IOZ7UTL6.cpp: bad whitespace in multiple lines
/home/robotex/sources/yunit/builddir/tests/mocks/Unity/FakeUnityQml_automoc.dir/moc_ExpandableFilt_FSTKSZVAJJRKO7.cpp: bad whitespace in line 111
/home/robotex/sources/yunit/builddir/tests/mocks/Unity/Launcher/MockLauncherPlugin_automoc.dir/moc_plugin_ADXQMHAXOOHDUW.cpp: bad whitespace in multiple lines
/home/robotex/sources/yunit/builddir/tests/mocks/Unity/Launcher/MockLauncherPlugin_automoc.dir/moc_MockQuickListM_OJHI5WXZV6OAOX.cpp: bad whitespace in line 105
/home/robotex/sources/yunit/builddir/tests/mocks/Unity/InputInfo/MockInputInfo_automoc.dir/moc_plugin_ADXQMHAXOOHDUW.cpp: bad whitespace in multiple lines
/home/robotex/sources/yunit/builddir/tests/mocks/Unity/Notifications/MockNotificationsPlugin_automoc.dir/moc_plugin_ADXQMHAXOOHDUW.cpp: bad whitespace in multiple lines
/home/robotex/sources/yunit/builddir/tests/mocks/Unity/Connectivity/MockConnectivity_automoc.dir/moc_plugin_ADXQMHAXOOHDUW.cpp: bad whitespace in multiple lines
/home/robotex/sources/yunit/builddir/tests/mocks/Unity/ApplicationMenu/FakeApplicationMenu-qml_automoc.dir/moc_applicationmen_6MYWZJ2USSKEVW.cpp: bad whitespace in line 112
/home/robotex/sources/yunit/builddir/tests/mocks/Unity/ApplicationMenu/FakeApplicationMenu-qml_automoc.dir/moc_plugin_ADXQMHAXOOHDUW.cpp: bad whitespace in multiple lines
/home/robotex/sources/yunit/builddir/tests/mocks/Unity/DashCommunicator/MockDashCommunicator-qml_automoc.dir/moc_plugin_ADXQMHAXOOHDUW.cpp: bad whitespace in multiple lines
/home/robotex/sources/yunit/builddir/tests/mocks/Unity/Application/FakeUnityApplicationQml_automoc.dir/moc_plugin_ADXQMHAXOOHDUW.cpp: bad whitespace in multiple lines
/home/robotex/sources/yunit/builddir/tests/mocks/Unity/Application/FakeUnityApplicationQml_automoc.dir/qrc_surfaces_QUFZ44VOKBSIYI.cpp: bad whitespace in lines 178086, 178200
/home/robotex/sources/yunit/builddir/tests/mocks/Unity/Application/NonMirUnityApplicationQml_automoc.dir/moc_plugin_ADXQMHAXOOHDUW.cpp: bad whitespace in multiple lines
/home/robotex/sources/yunit/builddir/tests/mocks/Unity/Application/NonMirUnityApplicationQml_automoc.dir/qrc_surfaces_QUFZ44VOKBSIYI.cpp: bad whitespace in lines 178086, 178200
/home/robotex/sources/yunit/builddir/tests/mocks/Unity/Indicators/IndicatorsFakeQml_automoc.dir/moc_fakeplugin_JAV53I6YZK3KIW.cpp: bad whitespace in multiple lines
/home/robotex/sources/yunit/builddir/plugins/Utils/Utils-qml_automoc.dir/moc_constants_DNUAWUW6YZXSSJ.cpp: bad whitespace in line 109
/home/robotex/sources/yunit/builddir/plugins/Utils/Utils-qml_automoc.dir/moc_plugin_ADXQMHAXOOHDUW.cpp: bad whitespace in multiple lines
/home/robotex/sources/yunit/builddir/plugins/Powerd/Powerd-qml_automoc.dir/moc_plugin_ADXQMHAXOOHDUW.cpp: bad whitespace in multiple lines
/home/robotex/sources/yunit/builddir/plugins/ScreenshotDirectory/ScreenshotDirectory-qml_automoc.dir/moc_plugin_ADXQMHAXOOHDUW.cpp: bad whitespace in multiple lines
/home/robotex/sources/yunit/builddir/plugins/LightDM/FullLightDM/FullLightDM-qml_automoc.dir/moc_plugin_ZO6Y7UZKU5LALY.cpp: bad whitespace in multiple lines
/home/robotex/sources/yunit/builddir/plugins/LightDM/IntegratedLightDM/IntegratedLightDM-qml_automoc.dir/moc_plugin_ZO6Y7UZKU5LALY.cpp: bad whitespace in multiple lines
/home/robotex/sources/yunit/builddir/plugins/Dash/Dash-qml_automoc.dir/moc_plugin_ADXQMHAXOOHDUW.cpp: bad whitespace in multiple lines
/home/robotex/sources/yunit/builddir/plugins/Greeter/Unity/Launcher/UnityLauncherAS-qml_automoc.dir/moc_plugin_ADXQMHAXOOHDUW.cpp: bad whitespace in multiple lines
/home/robotex/sources/yunit/builddir/plugins/GlobalShortcut/GlobalShortcut-qml_automoc.dir/moc_plugin_ADXQMHAXOOHDUW.cpp: bad whitespace in multiple lines
/home/robotex/sources/yunit/builddir/plugins/UInput/UInput-qml_automoc.dir/moc_plugin_ADXQMHAXOOHDUW.cpp: bad whitespace in multiple lines
/home/robotex/sources/yunit/builddir/plugins/Ubuntu/Gestures/UbuntuGesturesQml_automoc.dir/moc_plugin_ADXQMHAXOOHDUW.cpp: bad whitespace in multiple lines
/home/robotex/sources/yunit/builddir/plugins/Ubuntu/DownloadDaemonListener/DownloadDaemonListener_automoc.dir/moc_plugin_ADXQMHAXOOHDUW.cpp: bad whitespace in multiple lines
/home/robotex/sources/yunit/builddir/plugins/Wizard/Wizard-qml_automoc.dir/moc_plugin_ADXQMHAXOOHDUW.cpp: bad whitespace in multiple lines
/home/robotex/sources/yunit/builddir/plugins/AccountsService/AccountsService-qml_automoc.dir/moc_plugin_ADXQMHAXOOHDUW.cpp: bad whitespace in multiple lines
/home/robotex/sources/yunit/builddir/plugins/ImageCache/ImageCache-qml_automoc.dir/moc_plugin_ADXQMHAXOOHDUW.cpp: bad whitespace in multiple lines
/home/robotex/sources/yunit/builddir/plugins/Cursor/Cursor-qml_automoc.dir/moc_plugin_ADXQMHAXOOHDUW.cpp: bad whitespace in multiple lines
/home/robotex/sources/yunit/builddir/plugins/SessionBroadcast/SessionBroadcast-qml_automoc.dir/moc_plugin_ADXQMHAXOOHDUW.cpp: bad whitespace in multiple lines
/home/robotex/sources/yunit/builddir/plugins/Lights/Lights-qml_automoc.dir/moc_plugin_ADXQMHAXOOHDUW.cpp: bad whitespace in multiple lines
/home/robotex/sources/yunit/builddir/plugins/WindowManager/windowmanager-qml_automoc.dir/moc_WindowManagerP_WTZVRANYCZYWDA.cpp: bad whitespace in multiple lines
/home/robotex/sources/yunit/builddir/plugins/Unity/Session/UnitySession-qml_automoc.dir/moc_plugin_ADXQMHAXOOHDUW.cpp: bad whitespace in multiple lines
/home/robotex/sources/yunit/builddir/plugins/Unity/Launcher/UnityLauncher-qml_automoc.dir/moc_plugin_ADXQMHAXOOHDUW.cpp: bad whitespace in multiple lines
/home/robotex/sources/yunit/builddir/plugins/Unity/Platform/Platform-qml_automoc.dir/moc_plugin_ADXQMHAXOOHDUW.cpp: bad whitespace in multiple lines
/home/robotex/sources/yunit/builddir/plugins/Unity/InputInfo/InputInfo_automoc.dir/moc_plugin_ADXQMHAXOOHDUW.cpp: bad whitespace in multiple lines
/home/robotex/sources/yunit/builddir/plugins/Unity/Connectivity/Connectivity_automoc.dir/moc_plugin_ADXQMHAXOOHDUW.cpp: bad whitespace in multiple lines
/home/robotex/sources/yunit/builddir/plugins/Unity/ApplicationMenu/menuregistraradaptor.h: bad whitespace in line 3
/home/robotex/sources/yunit/builddir/plugins/Unity/ApplicationMenu/menuregistraradaptor.cpp: bad whitespace in line 3
/home/robotex/sources/yunit/builddir/plugins/Unity/ApplicationMenu/ApplicationMenu-qml_automoc.dir/moc_plugin_ADXQMHAXOOHDUW.cpp: bad whitespace in multiple lines
/home/robotex/sources/yunit/builddir/plugins/Unity/ApplicationMenu/ApplicationMenu-qml_automoc.dir/moc_applicationmen_CRXMHIHVIKHS4Y.cpp: bad whitespace in line 112
/home/robotex/sources/yunit/builddir/plugins/Unity/DashCommunicator/DashCommunicator-qml_automoc.dir/moc_plugin_ADXQMHAXOOHDUW.cpp: bad whitespace in multiple lines
/home/robotex/sources/yunit/builddir/plugins/Unity/Indicators/IndicatorsQml_automoc.dir/moc_plugin_ADXQMHAXOOHDUW.cpp: bad whitespace in multiple lines

**Comment by KoczurekK** [comment]
We have to fix whitespaces in those files to get `whitespace` test pass, it may take some time.

**Comment by NicholasShatokhin** [comment]
robotex@robotex-VirtualBox:~/sources/yunit/builddir$ ctest
Test project /home/robotex/sources/yunit/builddir
      Start  1: testAccountsService
 1/27 Test  #1: testAccountsService ..............   Passed    1.20 sec
      Start  2: testLauncherModelAS
 2/27 Test  #2: testLauncherModelAS ..............   Passed    0.52 sec
      Start  3: testGreeterIntegrated
 3/27 Test  #3: testGreeterIntegrated ............   Passed    0.21 sec
      Start  4: testSessionBroadcast
 4/27 Test  #4: testSessionBroadcast .............   Passed    0.31 sec
      Start  5: testAxisVelocityCalculator
 5/27 Test  #5: testAxisVelocityCalculator .......   Passed    0.05 sec
      Start  6: testIndicatorsManager
 6/27 Test  #6: testIndicatorsManager ............   Passed    0.08 sec
      Start  7: testIndicatorsModel
 7/27 Test  #7: testIndicatorsModel ..............   Passed    0.06 sec
      Start  8: testMenuContentActivator
 8/27 Test  #8: testMenuContentActivator .........   Passed    0.02 sec
      Start  9: testUnityMenuModelStack
 9/27 Test  #9: testUnityMenuModelStack ..........   Passed    0.03 sec
      Start 10: testRootActionState
10/27 Test #10: testRootActionState ..............   Passed    0.05 sec
      Start 11: testSharedUnityMenuModel
11/27 Test #11: testSharedUnityMenuModel .........   Passed    0.05 sec
      Start 12: testLauncherModel
12/27 Test #12: testLauncherModel ................   Passed    0.42 sec
      Start 13: testPlatform
13/27 Test #13: testPlatform .....................   Passed    5.97 sec
      Start 14: testSessionBackend
14/27 Test #14: testSessionBackend ...............   Passed    0.33 sec
      Start 15: testQLimitProxyModel
15/27 Test #15: testQLimitProxyModel .............   Passed    0.04 sec
      Start 16: testUnitySortFilterProxyModel
16/27 Test #16: testUnitySortFilterProxyModel ....   Passed    0.04 sec
      Start 17: testWindowInputMonitor
17/27 Test #17: testWindowInputMonitor ...........   Passed    0.05 sec
      Start 18: testDeviceConfigParser
18/27 Test #18: testDeviceConfigParser ...........   Passed    0.05 sec
      Start 19: testWindowStateStorage
19/27 Test #19: testWindowStateStorage ...........   Passed    0.12 sec
      Start 20: testUtilsStyle
20/27 Test #20: testUtilsStyle ...................   Passed    0.31 sec
      Start 21: testURLDispatcher
21/27 Test #21: testURLDispatcher ................   Passed    0.08 sec
      Start 22: testTopLevelWindowModel
22/27 Test #22: testTopLevelWindowModel ..........   Passed    0.07 sec
      Start 23: testWizardPageList
23/27 Test #23: testWizardPageList ...............   Passed    0.05 sec
      Start 24: testWizardSystem
24/27 Test #24: testWizardSystem .................   Passed    0.04 sec
      Start 25: Whitespace
25/27 Test #25: Whitespace .......................***Failed    4.66 sec
      Start 26: imports
26/27 Test #26: imports ..........................   Passed    2.03 sec
      Start 27: Copyright
27/27 Test #27: Copyright ........................   Passed    2.03 sec

96% tests passed, 1 tests failed out of 27

Total Test time (real) =  19.01 sec

The following tests FAILED:
	 25 - Whitespace (Failed)
Errors while running CTest

**Comment by NicholasShatokhin** [comment]
And I see only one deb at builddir unity8-build-deps_1.0_amd64.deb
Is it normal?

**Comment by NicholasShatokhin** [comment]
Oh, I forgot to say. I downloaded Qt5.8 from qt.io and installed it to /opt/Qt/. Then I set variables Qt5<Module>_DIR to correct ways.

**Comment by NicholasShatokhin** [comment]
Ok, I removed sources and cloned repository again. After this is successfully built and passed all tests.
But when I tried to build packages, the Whitespaces test has failed again.

```
96% tests passed, 1 tests failed out of 27

Total Test time (real) =  11.37 sec

The following tests FAILED:
	 25 - Whitespace (Failed)
Errors while running CTest
Makefile:130: recipe for target 'test' failed
make[1]: *** [test] Error 8
make[1]: Leaving directory '/home/robotex/sources/yunit/obj-x86_64-linux-gnu'
dh_auto_test: make -j2 test ARGS+=-j2 returned exit code 2
debian/rules:12: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
```

and there was no packages created.

Also I have an errors during packages build:

```
pragma Singleton
-------^
ERROR:root:Failed to parse /home/robotex/sources/yunit/qml/Greeter/LightDMService.qml
ERROR:root:Lexer error line 22: Expected '{' after base class name

pragma Singleton
-------^
/home/robotex/sources/yunit/plugins/Ubuntu/Gestures/AxisVelocityCalculator.cpp:31: warning: no matching class member found for 
  AxisVelocityCalculator::AxisVelocityCalculator(const SharedTimeSource &timeSource, QObject *parent)
Possible candidates:
  AxisVelocityCalculator::AxisVelocityCalculator(QObject *parent=0)
  AxisVelocityCalculator::AxisVelocityCalculator(const UG_PREPEND_NAMESPACE(SharedTimeSource) &timeSource, QObject *parent=0)
```

Looks like it doen't know what **pragma** means.

**Comment by KoczurekK** [comment]
You need to delete `tests/whitespace` and comment out `add_subdirectory(whitespace)` int `tests/whitespace/CMakeLists.txt`. I suggested removing this test entirely, but @jsalatas wants to keep it, so I guess we have to somehow fix it. It's even more sad, that sometimes it works and sometimes not. :\

**Comment by Leppan** [comment]
So if you had two identical versions of the project, and you ran the whitespace test, it would work in perhaps one but not the other?

**Comment by KoczurekK** [comment]
Those are my observations. But maybe I'm missing something.

**Comment by jsalatas** [comment]
@KoczurekK hmmm.... given the rate that it fails, maybe we should comment it out for now (do not remove it though). 

In any case we should be very strict about the source code formatting: we shouldn't accept any PR that changes the source code's formatting because of a specific IDE configuration (eg changing spaces to tabs or vice versa, etc).

**Comment by KoczurekK** [comment]
@jsalatas I already fixed it, it's not a nice solution, but at least `check_whitespace.py` always works. Check out my last PR.

Anyway, @NicholasShatokhin, it should be OK now, could you please pull changes from repo and run `ctest` again?

**Comment by konfou** [comment]
@NicholasShatokhin also put the fourth comment in code style as it references an unrelated issue.

**Comment by jsalatas** [comment]
Is this still pending? Can I close it?

**Comment by NicholasShatokhin** [comment]
Will check today

**Comment by KoczurekK** [comment]
Great, thanks. :)
W dniu czw., 20.04.2017 o 09:28 Nicholas Shatokhin <notifications@github.com>
napisał(a):
