### ISSUE TITLE
Unity8 interface review (a lot of screenshots)

### ISSUE THREAD

**Issue by NicholasShatokhin** [yunit-io/yunit#62]
Hello. I'm using Unity since it was invented and I'm a biggest fan of this Desktop Environment. News about it closing was painful. So, I want to help you to make Yunit the best DE in the world.

Yesterday, I tried the Unity8 and there is review about problems that don't allow me to use it every day.

1. Dash.

When I open Dash in Unity7, focus is always set to search. No matter what scope was opened, I see focus set to this field. So, it is very convenient: I can press Win-key and start typing immediately, without any using of mouse or pressing another key-combination:
 
![dash](https://cloud.githubusercontent.com/assets/643803/24993358/b222990a-202e-11e7-93eb-97de4561c6eb.png)

![dash_apps](https://cloud.githubusercontent.com/assets/643803/24993354/b21ca8d8-202e-11e7-8af5-ab4be582e869.png)

At Unity8 I also can open the Dash by pressing Win-key but there is no focus on the search field.

![screenshot20170412_231200954](https://cloud.githubusercontent.com/assets/643803/24993359/b230ade2-202e-11e7-8e86-a3a30aacff3a.png)

So, I need to press additionally to Search button to activate this field and start searching.

![screenshot20170412_231211141](https://cloud.githubusercontent.com/assets/643803/24993360/b234adca-202e-11e7-8b6e-07098bac95c2.png)

It is good behavior in the Phone/Tablet mode, but wrong in the Desktop mode. We should to activate search field immediately after Dash was opened in the Desktop mode. User should not to waste his time to mouse movement/key pressing.

Another problem with the Dash is that Dash is showed when system launched. It is correct in the Phone mode, but we should to hide it in Desktop and show only when Win-key pressed.

2. Launcher

At Unity 7 I can make my Launcher always visible:

![launcher_and_indicators](https://cloud.githubusercontent.com/assets/643803/24993353/b219d810-202e-11e7-9a2f-c37863b461bc.png)

I can't find how to do the same in the Unity8:

![screenshot20170412_231222763](https://cloud.githubusercontent.com/assets/643803/24993361/b237643e-202e-11e7-8882-e324d4ecaeaf.png)

It is ok in the Phone mode, but some users like when Launcher is always visible on Desktop. It not just launches apps, it also shows opened apps and indicators above the app icons. We need to add option to Settings to allow keeping Launcher visible in Desktop mode.

Also, I didn't find how to change size of the launcher icons.

3. Indicators

Look at the Top panel at Unity7:

![launcher_and_indicators](https://cloud.githubusercontent.com/assets/643803/24993353/b219d810-202e-11e7-9a2f-c37863b461bc.png)

You can see that I installed two additionally indicators: indicator-multiload and psensor. It is very convenient: indicators are always on top and I can see what happen with my system at any time. I understand, that we can't show it in Phone mode, but we can show just and icon in that case and show full indicator in the Desktop mode.
I can't live without this indicators. Unity8 should to keep this feature. Maybe, we need to write the new indicators (don't add the ability to install same indicators from Unity7), but we should to have this ability.

And I don't like how indicators look at the Desktop mode in Unity8. Just compare it with Unity7 indicators:

![date_time_indicator](https://cloud.githubusercontent.com/assets/643803/24993355/b21f1744-202e-11e7-9bf3-b85f8c24e52b.png)

and 

![screenshot20170412_231328851](https://cloud.githubusercontent.com/assets/643803/24993362/b23784f0-202e-11e7-8d68-1ec9135c0f40.png)

![networking_indicators](https://cloud.githubusercontent.com/assets/643803/24993357/b22272ae-202e-11e7-80fb-5e9e29f49243.png)

and

![screenshot20170412_231340424](https://cloud.githubusercontent.com/assets/643803/24993363/b23ade20-202e-11e7-964e-6f8f12665b44.png)

![volume_indicator](https://cloud.githubusercontent.com/assets/643803/24994609/4a085af2-2034-11e7-8151-bce52f495e5f.png)

and

![screenshot20170412_231336432](https://cloud.githubusercontent.com/assets/643803/24993364/b23ac426-202e-11e7-8819-09797d2a440b.png)

Indicators at Unity8 have bigger fonts and icons and use a lot of space. It is good in Phone/Tablet mode, but it looks ugly at Desktop mode. I think, we should to make it small in Desktop Mode, like in Unity7 (or add an option to allow user make decision by himself).

4. Windows

Windows are ok at Unity8 but I need to notice about proportions.

![screenshot20170412_231531267](https://cloud.githubusercontent.com/assets/643803/24994927/98a9eb66-2035-11e7-8f80-41553a83dba8.png)

![system_settings](https://cloud.githubusercontent.com/assets/643803/24993375/b277feae-202e-11e7-9b84-ef924ade8da7.png)

Windows at Unity8 keep the phone proportions but it should to have Desktop proportions in Desktop mode. So, I need to manually change the size of window when it opened and waste my time. And Terminal app looks ugly.

Also, there is no way to take Screenshot of separate window (alt+PrintScr) in Unity8. I understand that it is impossible in Phone mode but why not to add it in Desktop mode? Desktop should to offer more always.

And if we start talking about screenshots, at Unity7 there is a window that showing when you take screenshot:

![screenshots](https://cloud.githubusercontent.com/assets/643803/24993371/b2628f7e-202e-11e7-8b1f-2870e8226531.png)

So, you can choose name of file, saving destination or just copy it to clipboard. We need it in Unity8 at Desktop mode (Phone mode is ok).

Also, you can to set screenshot taking delay in Unity7:

![screenshot_delay](https://cloud.githubusercontent.com/assets/643803/24995013/e1280094-2035-11e7-8a45-f54d4bcf5e48.png)

It is very convenient some times and we need it in Unity8 too.

Also, these is no possibility to open context menu of Desktop at Unity8.

![right_click_on_desktop](https://cloud.githubusercontent.com/assets/643803/24993356/b22010f4-202e-11e7-87d2-7b12125e18ac.png)

Is it not a big problem, but convenient for changing desktop background or Launcher's icons size. I will not cry if this feature die, but I will glad if not )

5. Applications

When I finished to taking screenshots at Unity8 I found that I can't access it. I could not to open Nautilus. Also, I couldn't open Firefox. Why not? I want to use my desktop apps in Desktop mode. I understand, that I can't use it on ARM, but now Unity8 is installed on my laptop. So, I need a full access to all available apps.

6. What is awesome

Opened windows list looks awesome.

![screenshot20170412_231901126](https://cloud.githubusercontent.com/assets/643803/24993370/b254e324-202e-11e7-81c2-a7eb4f18490f.png)

I forgot to test is it working when I press Alt+Tab. It should.

Lock screen awesome too. But I don't see how to change Desktop Environment (for i.e. if I want to launch Gnome instead of Unity for some purposes).

![screenshot20170412_232130995](https://cloud.githubusercontent.com/assets/643803/24993368/b25263ba-202e-11e7-8414-17f4b88d4d25.png)

C++ and QML are awesome. I hated Python in Unity7.

Unity8 has a great potential but it needs some modifications.
I want to start using it as my main Desktop Environment as soon as possible. It will allow me to collect bugs and problems at early stages. When you are using something everyday, you can find more problems that can be hidden when you run it just for tests.

I hope, my report will help you.

**Comment by markures** [comment]
I think that you are using an old version of Unity 8, now it has a Drawer that looks very similar to the Unity 7 Dash. Also, the Alt Tab switcher doesn't show the workspace but only apps ( they were working to enhance and reintroduce it by the way )

**Comment by NicholasShatokhin** [comment]
Khmmm. So, I need to build latest Yunit and look again. I built it yesterday but can't run it yet. What is about another issues?

**Comment by salvprest** [comment]
to see the actual version of Unity 8 I suggest you to watch the videos of Popescu Sorin https://www.youtube.com/user/pixelr0/videos

**Comment by KoczurekK** [comment]
Such reviews shouldn't be posted here, [r/yunit](https://www.reddit.com/r/Yunit/) is a place for that and AFAIK you already [published it there](https://www.reddit.com/r/Yunit/comments/6547hl/unity8_interface_review/).
