### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by yzinets** [yunit-io/yunit#76]
VirtualBox 5.1
System: Ubuntu 17.04
All dependencies are installed.
Log in file.
[log.txt](https://github.com/yunit-io/yunit/files/929892/log.txt)

**Comment by KoczurekK** [comment]
Fixed. 4e076fe3dea6276e64a8de89983b2b1cd8b98be0

**Comment by yzinets** [comment]
[ 13%] Generating id.gmo
/home/unity8/yunit/po/id.po:724: end-of-line within string
/home/unity8/yunit/po/id.po:840: end-of-line within string
/usr/bin/msgfmt: found 2 fatal errors
po/CMakeFiles/pofiles_42.dir/build.make:60: recipe for target 'po/id.gmo' failed
make[2]: *** [po/id.gmo] Error 1
CMakeFiles/Makefile2:39484: recipe for target 'po/CMakeFiles/pofiles_42.dir/all' failed
make[1]: *** [po/CMakeFiles/pofiles_42.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Generating moc compilation Wizard-qml_automoc.cpp
[ 13%] Built target Wizard-qml_automoc
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by KoczurekK** [comment]
Fixed again (8618af149cb89867b25a3450e329b4bb9258a8e1) and this time tested. :grinning:

**Comment by KoczurekK** [comment]
So… I guess I can close it, right?
