### ISSUE TITLE
 Preliminary plan to stabilize the work of Yunit

### ISSUE THREAD

**Issue by VlasovRoman** [yunit-io/yunit#77]
Hey everyone!

I want to propose a plan for stabilizing the DE for the near future.

1. The first thing that we must do, in my opinion, is to ensure the work of the environment in the Arch ecosystem. Most packages in it are distributed by how-is. So we'll untie the shell from the patched canon packets. Ie, if we make it work for Arch, it can be a priori run on any distro.

2. After that, you can already think about rebranding the shell. Basically, the code itself.

3. After rebranding, you can begin the basic development. I suggest the following concept as ideal. #17 

P.S. Sorry for the errors, I used Google.Translate

**Comment by Leppan** [comment]
This.
But we also need to think about apps. After all, this is also going to be going on phones.

**Comment by VlasovRoman** [comment]
And yet, linking to the Canonicals patchset will not bring anything good. Most missing functions can be configured as separate packages. Binding to Arch code base, I think, will give more opportunities for work in other conditions, even on phones.

**Comment by Leppan** [comment]
It already works on phones. This is literally Ubuntu touch. I get what you mean. I meant to simply consider apps as a longer term goal.

**Comment by jsalatas** [comment]
There is already another "issue" about yunit in arch.
