### ISSUE TITLE
Rename repository to "unity8"?

### ISSUE THREAD

**Issue by z3ntu** [yunit-io/yunit#8]
Organization name is fine but I think the repo shouldn't be called unity8org but unity8.

Also the rename in the early stages where not everything is linked everywhere should be painless-er

**Comment by jsalatas** [comment]
Not sure about that. Did you checked about any trademarks? :)

**Comment by jsalatas** [comment]
Can we please continue the discussion at the mailing list? :)

https://unity8.org/cgi-bin/mailman/listinfo/dev

**Comment by z3ntu** [comment]
No I have no idea.

**Comment by jsalatas** [comment]
So I guess unity8org is a safe bet here (see X11 -> Xorg) :)
