### ISSUE TITLE
Question about covergence and mobile

### ISSUE THREAD

**Issue by owais** [yunit-io/yunit#84]
Is yunit going to focus on Canonical's convergence vision and try to be both a mobile and desktop environment or drop mobile and focus on creating a great desktop experience? A true upgrade to Unity7 if you will.

**Comment by criztovyl** [comment]
afaik Yunit is focusing onto the desktop, but w/o dropping mobile. Mobile is dobe by UBPorts.
I think the question about convergence both projects will have to decide together.

**Comment by jsalatas** [comment]
We will keep convergence.

**Comment by owais** [comment]
Thanks for clarifying. I personally believe it would be better if desktop is given the priority. There is a real market for Yunit there. Not so sure about mobile unfortunately.
