### ISSUE TITLE
dev mailing list is down

### ISSUE THREAD

**Issue by 3DJetengine** [yunit-io/yunit#9]
So I clicked here:

https://yunit.io/cgi-bin/mailman/listinfo/dev

and filled out the form.

only to realize that the mailing had been taken away ?

please reinstate mailing list for devs.

thank-you.
![yunit mailman screenshot](https://user-images.githubusercontent.com/29660261/28342922-9d7388e0-6c12-11e7-8110-c6135abae111.png)

**Comment by jsalatas** [comment]
It's not down. It just seems that no one is using it :(

**Comment by 3DJetengine** [comment]
well I have a gmail - and I am not getting the subscription link to join - so whats the problem ?

**Comment by jsalatas** [comment]
OK! That's a different story. I need to look at it.....

**Comment by jsalatas** [comment]
Seems that gmail is considering it as a spam. I'll check and fix it. 
In the mean time, please check your spam folder.

**Comment by jsalatas** [comment]
Should be fixed now.

PS: please use https://github.com/yunit-io/website/ for reporting issues related to the infrastructure (websites, mailing lists, etc) in the future. 

Thanks
