### ISSUE TITLE
Make a map or graph of the yunit code

### ISSUE THREAD

**Issue by salvprest** [yunit-io/yunit#96]
wee don't know the Yunit code, I haven't much time to be an active developer, but if someone that is studing this code make a good documentation of the general structure of the code maybe will be much simple to help (would be interesting see what part of the code depend directly from Mir, for example)

**Comment by jsalatas** [comment]
This is what I'm currently working. Hope to have an update soon....

**Comment by MggMuggins** [comment]
How this that coming? I'd be interested in seeing a codemap as well.

**Comment by jsalatas** [comment]
see here 
https://forum.yunit.io/viewtopic.php?f=6&t=27

sorry forgot to post it here and I may forget again. So please keep an eye in the for anything that is not a bug or feature request.
